### PR TITLE
I tried to update Offsets

### PR DESCRIPTION
**Pull request by B3ni15**

### CODE REVIEW

**Comment by kmordike** [comment]
Change dwPlantedC4 to "48 8B 15 ?? ?? ?? ?? FF C0"

**Comment by B3ni15** [comment]
I think i did it. What's next?

**Comment by kmordike** [comment]
It will compile and run but the rest of the patterns are wrong lmao. Ill update them and lyk

**Comment by B3ni15** [comment]
Okay! Thanks bro :D

**Pull request closed without merging**
